-- 전체 조회용
SELECT * FROM BOOK;

-- 테이블 생성
CREATE TABLE BOOK(
	BOOK_NO NUMBER CONSTRAINT BOOK_NO_PK PRIMARY KEY,
 	CALL_NO NUMBER CONSTRAINT CALL_NO_UQ UNIQUE,
	BOOK_NAME VARCHAR2(60) CONSTRAINT BOOK_NAME_NN NOT NULL,
	AUTHOR VARCHAR2(45),
	PUBLISHER VARCHAR2(45),
	LOCATION VARCHAR2(30) CONSTRAINT LOC_NN NOT NULL,
	AVAILABILITY VARCHAR2(15) CONSTRAINT AVL_CK CHECK( AVAILABILITY IN ('대출가능', '대출중', '대출불가', '분실/파손')),
	DUE_DATE DATE
);

-- 시퀀스 생성
CREATE SEQUENCE SEQ_BOOK_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

-- SEQ_BOOK_NO.NEXTVAL;
-- SEQ_BOOK_NO.CURRVAL;

-- 수정1
ALTER TABLE BOOK MODIFY CALL_NO VARCHAR2(30);
INSERT INTO BOOK VALUES(1, '000.0가00ㄱ가ㄱ', '제목1', '저자1', '출판사1', '1층', '대출가능', NULL);

-- 수정2
ALTER TABLE BOOK MODIFY AVAILABILITY DEFAULT '대출불가';

---------------------------------
-- 테스트
SELECT * FROM BOOK
WHERE BOOK_NAME = '제목1' OR AUTHOR = '제목1';
